### ISSUE TITLE
Slimes Not Dropping Slime Balls

### ISSUE THREAD

**Issue by Asuraian** [frikinjay/morefrogs#9] opened 2022-10-04 16:25 UTC
Had an issue making a slime farm, afking and not getting any drops. Ran vanilla, drops started. Went through my mods 1 by 1 and this one causes them to stop dropping slime balls. Using mod version morefrogs-1.19.x-1.2.3-fabric.jar, Minecraft version 1.19.2, Fabric 0.14.9

**Comment by Malderest** [comment] 2022-10-06 05:10
This appears to be caused by an incomplete update to add in a new frog type (lush_warden). I've encountered similar issues with a log file reporting an incorrect call from the **slime entity drop list**. After looking through the files it seems like the lush_warden wasn't given the right calls for spawning or texturing yet still has a listing for what a slime should drop when it gets damaged by a frog. The class file "MoreFrogsMod.class" located at "morefrogs-1.19.x-1.2.3-fabric.jar\com\frikinjay\morefrogs\" does not have a reference to the texture file used for the new variant while every other frog is listed. I assume there will probably be more missing references elsewhere in the mod.

This is the relevant log listing for the current selection of mods I use:
[21:11:04] [Render thread/ERROR]: Couldn't parse loot table minecraft:entities/slime
com.google.gson.JsonSyntaxException: Unknown variant: morefrogs:lush_warden
	at net.minecraft.class_7380.method_43115(class_7380.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_7376.method_43097(class_7376.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_2048.method_8913(class_2048.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_2022.method_8846(class_2022.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_190$class_191.method_839(class_190.java:53) ~[client-intermediary.jar:?]
	at net.minecraft.class_190$class_191.method_517(class_190.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:473) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_29319(class_79.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15272(class_3518.java:463) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_3518.method_15291(class_3518.java:455) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15283(class_3518.java:473) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.method_340(class_52.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_52$class_54.deserialize(class_52.java:210) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_60.method_20711(class_60.java:44) ~[client-intermediary.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraft.class_60.method_20712(class_60.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_60.method_18788(class_60.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41900(class_7196.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41891(class_7196.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41899(class_7196.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.handler$zgc000$wt_callFixerOnLoad(class_7196.java:548) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41894(class_7196.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:528) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:436) ~[client-intermediary.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:367) ~[client-intermediary.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:359) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:491) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) [lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1174) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]

**Comment by frikinjay** [comment] 2022-10-12 11:24
This was a snippet of code left in while working on the upcoming update. Fixed in 1.2.3a

**Closed as completed by frikinjay** 2022-10-12 11:24 UTC
